platform :ios, '8.0'
target '澳門物管BMS' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'JPush'
pod 'MMDrawerController'
pod 'MJExtension'
pod 'pop'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'MJRefresh'
pod 'SDCycleScrollView'
pod 'Bugly'
end
